### ISSUE TITLE
DELTA NOT MOVING PROPERLY

### ISSUE THREAD

**Issue by 3ddev-j** [TTN-/IcePick-Delta#2]
Hi TTN, you have made a really nice project in this delta inverse kinematics firmware, but i'm in doubt on some codelines of your marlin that are driving me crazy on my delta printer.

first of all, i'm not good in english its dificult to me understand some words on yours coment at marlin v1.1, so....

Could you please explain me what kind of measures i should do on this first code part, to get my printer working?

// Enable DELTA kinematics and most of the default configuration for Deltas
#define DELTA

// NOTE NB all values for DELTA_* values MUST be floating point, so always have a decimal point in them

// Make delta curves from many straight lines (linear interpolation).
// This is a trade-off between visible corners (not enough segments)
// and processor overload (too many expensive calulations).
#define DELTA_SEGMENTS_PER_SECOND 40

// Horizontal offset of the pulley axle centres from the mounting plate centre
#define BASE_RADIUS 80.600
![2](https://user-images.githubusercontent.com/26746777/27570582-ae7d58bc-5ad5-11e7-9e9d-ef93f6facc31.png)
![1](https://user-images.githubusercontent.com/26746777/27570583-ae8066b0-5ad5-11e7-8b03-301319346b37.png)

 // you mean the center of machine to each pulley (large ones) center?

// what is the meaning of mouting plate? is the heatbed? 

// Horizontal radius of the end effector centre to the tangentline where the joints are
// making this value large will make prints scale larger in xy direction as z gets higher  
#define END_EFFECTOR_RADIUS 20.000 // 20.0mm for kossel end effector (used in the icepick delta)

// Center-to-center distance of the holes in the diagonal push rods.
// this has to EXACT. 1mm off and the hotend will far be too high or low in the middle of the printbed relative to edges
#define DELTA_DIAGONAL_ROD 325.000 // distance of the carbon fiber rods center to center?

// upperarm length
// if your hotend is close/too far from the bed near the edges, check this is correct
#define DELTA_ARM_LENGTH 160.000// i used original icepick one

// distance from home position to bed. 
// if this value doesn't adjust linearly for you, it means DELTA_DIAGONL_ROD and/or DELTA_ARM_LENGTH is wrong
#define Z_HOME_HEIGTH 265.580
// what does linearly" means?

// vertical distance from vertical midpoint of the end effector to mounting plate 
// this controls whether objects get narrower or wider as it gets taller
// and if set incorrectly, will contribute to the end effector not moving across the bed linearly
// towards the edges of the print bed this will become more apparent
// will also affect how far the machine thinks it can reach
// Too large value: leaning outward
// Too small value: leaning inward
#define END_EFFECTOR_TO_MOUNTPLATE 34.0

// this should be the same as Z_HOME_HEITGH? 

// vertical distance from the pulley axles to the mounting plate
#define PULLEY_MOUNT_HEIGHT 448.00

Tnks!

Have i nice day hope u understood me :)

**Comment by TTN-** [comment]
Hi, sorry I never got back to you. Better late than never?
Its been 2 years since I wrote this code so I'll do my best to remember.

Base radius:
So if you draw a circle going through all of the big pulley axle holes, that is the radius we are talking about.

----|||---- <- pulley1 on axle. Base radius is distance from this axle to the center
       |
       |    
     /  \
   /      \
2          3  <- pulleys 2 and 3

> // you mean the center of machine to each pulley (large ones) center?

Yes.

>// what is the meaning of mouting plate? is the heatbed?
For me all the pulleys are mounted to a wooden plate. This variable is the distance from that plate to my pulley axle centers. You can just set it to 0.0 for your case.

>#define DELTA_DIAGONAL_ROD 325.000 // distance of the carbon fiber rods center to center?

Yes.


>// what does linearly" means?

![image](https://user-images.githubusercontent.com/6019316/32410059-2fa9c85e-c21d-11e7-94da-ea148bb272a6.png)
I think its best explained like this.



>#define END_EFFECTOR_TO_MOUNTPLATE 34.0
>// this should be the same as Z_HOME_HEITGH?

This is the distance from your effector rod screw holes to your mounting plate. You can just use the distance from your effector rod screw holes to the center of your axles.

This machine is a pain in the !@#$ to calibrate. Its very time consuming but I managed to get in 0.2mm spec. It takes a lot of work. All the variables have comments explaining what changing it does but if you have more questions do ask and I will make an effort to reply in a timely manner.

**Comment by TTN-** [comment]
Explained as required :-) if you have any more questions, please reopen this issue or file a new one, thanks!
